### ISSUE TITLE
JWT::InvalidPayload with jwt 2.2.1

### ISSUE THREAD

**Issue by ericsaupe** [skukx/solidus_jwt#9]
Updating gems has caused `generate_jwt_token` to fail with the latest version of the `jwt` gem

```
Test Test [4] sigurd(#<RSpec::ExampleGroups::SpreeApiSessionsController::GETLogin>)> user.generate_jwt_token
JWT::InvalidPayload: iat claim must be an Integer but it is a String
from /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/claims_validator.rb:30:in `validate_is_int'
```

**Comment by skukx** [comment]
@ericsaupe Can you post the whole stack trace?

**Comment by ericsaupe** [comment]
```
JWT::InvalidPayload:
       iat claim must be an Integer but it is a String
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/claims_validator.rb:30:in `validate_is_int'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/claims_validator.rb:25:in `block in validate_int_claims'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/claims_validator.rb:24:in `each'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/claims_validator.rb:24:in `validate_int_claims'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/claims_validator.rb:16:in `validate!'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/encode.rb:48:in `encode_payload'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/encode.rb:30:in `encoded_payload'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/encode.rb:38:in `encoded_header_and_payload'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt/encode.rb:20:in `segments'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/jwt-2.2.1/lib/jwt.rb:24:in `encode'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/solidus_jwt-0.0.1/lib/solidus_jwt/concerns/encodeable.rb:19:in `encode'
     # /Users/ericsaupe/.rvm/gems/ruby-2.6.3@sigurd/gems/solidus_jwt-0.0.1/app/models/spree/user_decorator.rb:8:in `generate_jwt_token'
```
